const prompts = [
  ["hi", "hey", "hello"],
  ["good morning"],
  ["good afternoon"],
  ["good evening"],
  ["how are you", "how is life", "how are things"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  [
    "your name please",
    "your name",
    "may i know your name",
    "what is your name",
    "what call yourself"
  ],
  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["bad", "bored", "tired"],
  ["help me", "tell me story", "tell me joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "good bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no","not sure","maybe","no thanks"],
  [""],
  ["haha","ha","lol","hehe","funny","joke"],
  ["something about my university","my university","j.c. bose university","jc bose ust","jc bose university", "which year jc bose university established"],
  ["history","history of my university","history of university","history of jc bose university","history of j.c. bose ust","history of j.c. bose university"],
  ["campus","campus life","university campus life","university life","know more about campus","campus details"],
  ["location", "where is situated","location of university"],
  ["academic","academics","academics details","full academic structure","academic structure","courses offered","academic background"],
  ["ranking","nirf ranking","university ranking","college ranking","my university ranking"],
  ["student life","stuent activities","for students"],
  ["cultural societies"],
  ["ananya"],
  ["vividha"],
  ["jhalak"],
  ["tarannum"],
  ["natraja"],
  ["eklavya"],
  ["technical societies"],
  ["manan"],
  ["microbird"],
  ["hostel","hostel life","details about hostel","details of hostel","university hostel","jc bose university hostel"],
  ["boys hostel"],
  ["girls hostel"],
  ["eligiblity criteria","qualification for admission","eligiblity"],
  ["btech"],
  ["bca"],
  ["bba"],
  ["mtech"],
  ["mba"],
  ["msc"],
  ["mca"],
  ["admission process","admission process of university", "admission process of jc bose university"],
  ["ug admission"],
  ["pg admission"],
  ["scholarship details", "scholarship"]  
]

// Possible responses, in corresponding order

const replies = [
  ["Hello!", "Hi!", "Hey!", "Hi there!","Howdy"],
  ["Good morning buddy"],
  ["Good afternoon buddy"],
  ["Good evening dear"],
  [
    "Fine... how are you?",
    "Pretty well, how are you?",
    "Fantastic, how are you?"
  ],
  [
    "Nothing much",
    "About to go to sleep",
    "Can you guess?",
    "I don't know actually"
  ],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],
  ["The one true God, JavaScript"],
  ["I am nameless", "I don't have a name"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["Bye", "Goodbye", "See you later"],
  ["Sushi", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok","I understand","What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!","Good one!"],
  ["J.C. Bose University of Science and Technology, YMCA, formerly YMCA University of Science and Technology (YMCA UST) and YMCA Institute of Engineering (YMCAIE), is a state public university located in Faridabad, in the state of Haryana, India. Established as a college in 1969, it gained university status in December 2009 and was renamed in 2018."],
  ["J.C. Bose University was established in 1969 as an Indo-German project, a joint venture of the National Council of YMCAs of India, the Government of Haryana and the German Central Agencies for Development Aid, Bonn, Germany.[1] It was affiliated to M.D. University.[2] In 1996 the state government took full control over the college.[1] In 2009 it became a university through the YMCA University of Science and Technology Faridabad Act, 2009.[3] In 2018 it was renamed to its current name through the YMCA University of Science and Technology Faridabad (Amendment) Act, 2018."],
  ["The campus of the J.C. Bose University of Science and Technology, YMCA has three main buildings, one for MBA and the remaining two for other science and technology courses. Girl's hostel, Boy's Hostel and a library named Deen Dayal Upadhyay Library. There is an auditorium in the MBA block (1st floor), an auditorium cum indoor badminton courts (commonly known as Shakuntalam), a canteen, a café, a stationery shop, an Indian Overseas bank and a Mother Dairy which remains open during university hours. Sports amenities include a basketball court, two badminton courts inside the auditorium, a football/cricket ground and an archery area. A free dispensary is also there which opens during university hours."],
  ["The university is located at  6, Mathura Road, Sector 6, Faridabad, Haryana. The nearest railway station is Escorts Mujesar. Nearest Railway Station located  5 km away from the university and will take around 10 minutes to reach. Indira Gandhi International Airport is the nearest airport located at a distance of 45 km away. Students can take a bus or a cab to reach the university."],
  ["YMCA University offers undergraduate B.Tech and graduate Master of Technology (M.Tech) courses in various engineering fields. It also offers other postgraduate courses offering Master of Science, Master of Arts and Master of Business Administration, Master of Computer Applications degrees.The University also offers three-year degree courses like Bachelor of Computer Application (BCA), Bachelor of Business Administration (BBA), Bachelor of Science in subjects Physics, Chemistry, Maths, and Animation & Multimedia."],
  ["The National Institutional Ranking Framework (NIRF) ranked it 151 among engineering colleges in 2022 with A+ grade."],
  ["There are various cultural as well as technical clubs/societies of which the students can be a part of. YMCA University holds several annual festivals. 'ELEMENTS CULMYCA' is the annual cultural festival, which takes place in mid March where young students from all over India showcase their talents.KHOJ, the annual technical festival, involves students from technical institutions from the country. CONCOURSE is the annual sports meet.There are various student societies, cultural as well as technical for all-round development of the students. These student-run societies are encouraged by the university to further develop the character and personality traits and broaden the horizon of the students.To know more about, Search:cultural societies(for diffrent culturals clubs), Search:technical societies(for different technical clubs)"],
  ["Cultural societies: 1)Ananya, The Unparalleled; 2)Vividha - The Dramatics; 3)Jhalak - The Photography Club; 4)Tarannum - The Music Club; 5)Natraja - The Dancing Club; 6)Eklavya - The Sports Club.  To know more about these clubs - Type 'Only First-Name' given to these clubs properly. "],
  ["Cultural societie: Ananya, The Unparalleled: The Lit-Deb Soc: This is the Literary and Debating Society of the University and has won many accolades in various inter-college competitions and fests in the fields of Conventional Debates, Parliamentary Debates, MUNs, JAMs, Extempore, Poetry, Creative Writing, etc.  The society also maintains a board known as 'Furore' where various write-ups are put up by the members of the society along with recent achievements of its members. Senior members mentor the Juniors to participate and win competitions. This exposure leads the members to become excellent public speakers and gives them confidence which helps them everywhere, from interviews to life overall. Ananya, The Unparalleled is also responsible for hosting major events of the college like The Foundation Day, College Fests, Induction, Freshers etc. Along with that, this society also organizes various competitions from time to time which attracts pan-India participation."],
  ["Cultural societie: Vividha - The Dramatics: This is the Dramatics Society of the University and has participated and won in many inter-college competitions, they educate students of the university on social causes through their dramas and skits and also perform on important events of the university like, Foundation Day, Fests etc."],
  ["Cultural societie: Jhalak - The Photography Club: This club covers all the events of the university and are responsible for capturing all kinds of memories and emotions that run through the campus. Seniors mentor and inspire juniors to hone their photography skills."],
  ["Cultural societie: Tarannum - The Music Club: This club with its tune, melody and fervor and adds into the vibrancy of the University."],
  ["Cultural societie: Natraja - The Dancing Club: This club revolves around dance and guides its members to perform in an excellent way on important events of the university and also compete in inter college competitions."],
  ["Cultural societie: Eklavya - The Sports Club: It is the sports club of the university."],
  ["Technical Societies: 1)Manan, A Techno Surge: The Tech Soc; 2)Microbird - The Techno Club. To know more about these clubs - Type 'Only First-Name' given to these clubs properly. "],
  ["Technical Societie: Manan, A Techno Surge: The Tech Soc: This is the Information Technological Society of the University and has won many accolades in various inter-college competitions, fests and hackathons. This club is the most reputed club in the university in the field of technology because of its skilled and talented members. Almost all of its club members get placed in the top companies like Amazon, Samsung etc., that come in university, with a handsome package. The students can get entry in the club through its entrance test, Manthan, followed by a Project showcasing round and a P.I. round."],
  ["Technical Societie: Microbird - The Techno Club: This is the also the Technical club of University "],
  ["YMCA University has eight hostels in total. These are Boys Hostel and Girls Hostel. To know more about: Type - 'boys hostel'(for Boys Hostel information); Type - 'girls hostel'(for Girls Hostel information) "],
  ["Boys' Hostels: 1) Zakir Hussain Hall (40 rooms); 2) Tagore Hall (40 rooms); 3) CV Raman Hall (40 rooms); 4) Nehru Hall (40 rooms)"],
  ["Girls Hostel: 1) Kalpana Chawla Hall (28 rooms); 2) Sarojini Hall (21 rooms); 3) Mother Teressa Hall (22 rooms); 4) Kasturba Hall (22 rooms) "],
  ["The university offers many UG and PG courses. For more informations of courses: For B.tech(type btech); For BCA(type bca); For BBA(type bba); For M.Tech(type mtech); For MBA(type mba); For M.Sc.(type msc); For MCA(type MCA); For Ph.D(type phd) "],
  ["Candidates must have passed class 12th with Physics and Mathematics as compulsory subjects along with one of the Chemistry/ Biotechnology/ Biology/ Technical Vocational subjects with a minimum of 45% marks in aggregate from a recognised board."],
  ["Candidates must have passed the 10+2 examination or equivalent examination from any recognised board with 45% marks in aggregate."],
  ["Candidates must have passed 12th with a minimum of 50% marks from a recognised board."],
  ["Candidates must have passed B.E/B.Tech or equivalent degree in relevant branch with a minimum of 50% marks from a recognised university."],
  ["Candidates must have passed a bachelor’s degree in any stream with a minimum of 50% marks from a recognised university."],
  ["B.Sc./ B.Sc. (Hons.) with 50% marks in aggregate with relative subjects from a recognised university."],
  ["B.C.A or equivalent degree from a recognised university with 50% marks in aggregate. Or Candidates must have passed B.Sc./ B.Com./ B.A with 50% marks studied mathematics at the 10+2 or graduation level."],
  ["J.C. Bose University of Science and Technology admission process information: For B.Tech(type -> 'ug admission'); For MBA and MSC(type -> 'pg admission') "],
  ["UG admission: 1) Meet the eligibility criteria. 2) Fill Haryana B.Tech application form HSTES. 3) Haryana B.Tech admissions are based on JEE Main scores and marks obtained in class 10 +2 examination. 4) Shortlisted candidates whose names are on the merit list must appear for HSTES counselling. 5) Choose J.C. Bose UST Faridabad as the preferred university at the time of registration for HSTES counselling. 6) Candidates must visit the specific venue for document verification."],
  ["PG admission: 1) Eligible students must apply for admission by filling the application form. 2) Appear for the entrance examination conducted by the university. 3) For M.B.A. admissions,  shortlisted candidates have to appear for group discussion and personal interview. 4) Admissions will be offered based on the performance in the entrance exam, university-level document verification and payment of the fees."],
  ["The university offers an array of scholarships to its students. J.C. Bose UST Faridabad scholarships are offered on a need and merit basis. YMCA Faridabad scholarships include university scholarships, scholarships offered by other institutions/funding agencies, UGC, AICTE, government-funded scholarships. YMCA Faridabad scholarships are  Merit-Cum-Means, BC Post Matric Scholarship, SC Post Matric Scholarship RKM Scholarship, Guru Harkrishan Educational Society Scholarship, Vishwa Prakash Mission, MOB Scholarship, to name a few."] 
]

// Random for any other user input

const alternative = [
  "Same",
  "Go on...",
  "Bro...",
  "Try again",
  "I'm listening...",
  "I don't understand :/"
]

// Whatever else you want :)

const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]